---
- name: Install Apache, a web server
  hosts: all
  tasks:
    - name: Install Apache web server
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Create index.html file in html root directory
      ansible.builtin.copy:
        content: "<!DOCTYPE html> <html> <body> <h1>Foobar.</p></body></html>\n"
        dest: /var/www/html/index.html
        mode: '644'
        owner: apache
        group: apache

    - name: Enable and start Apache service across reboot
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
...
