---
driver:
  name: docker
dependency:
  name: galaxy
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  - name: ubi9-instance
    image: ubi9/ubi-init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    cgroupns_mode: host
    privileged: true
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
verifier:
  name: ansible

